FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y gunicorn python3-dev 



WORKDIR /app

COPY ./miniadmin/requirements.txt /app

RUN pip3 install --upgrade pip && pip3 install -r /app/requirements.txt

COPY ./miniadmin /app

CMD ["bash"]
