version: '3'

services:
  miniadmin:
    image: jasonly000/dockerhub.miniadmin:v1.2
    working_dir: /app
    expose:
      - 8008
    ports:
      - "8008:8008"
    restart: always
    volumes:
      - /mini:/mini
      - ./app/staticfiles:/app/staticfiles
    command: gunicorn --bind 0.0.0.0:8008 --workers 1 mini_admin.wsgi:application

  miniadmin_mining_queue:
    image: jasonly000/dockerhub.miniadmin:v1.2
    command: celery -A mini_admin.celery_app worker -Q mining_queue -n mini_admin@mining_queue --loglevel=INFO -B 
    restart: always
    # volumes:
    #   - /sds-filestore1/sds_admin/media:/app/media
    #   - /sds-filestore1:/sds-filestore1
    #   - /sds-filestore1/tmp/sds_admin:/tmp
    # env_file:
    #   - ./.env_job
    depends_on:
      - miniadmin

  nginx:
    image: nginx:1.13
    ports:
      - 8081:8081
    restart: always
    volumes:
      - ./miniadmin/nginx_admin/conf.d:/etc/nginx/conf.d
      - ./miniadmin/static:/app/static
      - ./miniadmin/media:/app/media
      - ./miniadmin/uploads:/app/uploads
    depends_on:
      - miniadmin
      
